create table if not exists public.message_board_messages (
  id bigint generated by default as identity primary key,
  author text not null default '匿名来客',
  content text not null,
  created_at timestamptz not null default now(),
  is_hidden boolean not null default false
);

create table if not exists public.message_board_replies (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.message_board_messages(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  is_hidden boolean not null default false
);

alter table public.message_board_messages enable row level security;
alter table public.message_board_replies enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.message_board_messages to anon, authenticated;
grant select on table public.message_board_replies to anon, authenticated;
grant usage, select on sequence public.message_board_messages_id_seq to anon, authenticated;
grant usage, select on sequence public.message_board_replies_id_seq to anon, authenticated;

drop policy if exists "public can read visible messages" on public.message_board_messages;
create policy "public can read visible messages"
on public.message_board_messages
for select
using (is_hidden = false);

drop policy if exists "public can insert messages" on public.message_board_messages;
create policy "public can insert messages"
on public.message_board_messages
for insert
with check (
  is_hidden = false
  and char_length(author) between 1 and 20
  and char_length(content) between 1 and 240
);

drop policy if exists "public can read visible replies" on public.message_board_replies;
create policy "public can read visible replies"
on public.message_board_replies
for select
using (is_hidden = false);

create index if not exists idx_message_board_messages_created_at
  on public.message_board_messages(created_at desc);

create index if not exists idx_message_board_replies_message_id
  on public.message_board_replies(message_id, created_at asc);
